### PR TITLE
Add github actions CI

### PR DESCRIPTION
**Pull request by casey**
I'm not sure if you've considered using GitHub Actions to do CI, but it's easy enough, so I thought I'd write a PR that adds it.

I mostly copy-pastaed this from another project, so don't feel bad if you'd prefer not to merge it for whatever reason.

Adds a github actions workflow that:

- Runs on ubuntu. Since this crate doesn't include any platform-specific
  code, it seems unnecessary to run on macOS and Windows, although that
  could easily be added.

- Fails if rust produces any warnings.

- Caches the cargo registry, cargo index, and build folder.

- Runs tests with default features, no default features, and with the
  serde feature.

- Runs clippy.

Clippy had some minor complaints, so I also fixed those.

### CODE REVIEW

**Comment by casey** [comment]
This PR won't trigger a github actions run, I think because it's against a repo that isn't main, and there isn't a workflow already in the master branch. (Honestly not sure how that works, that's just a guess.) But I was able to get a run to trigger by opening a PR against my own fork, so you can see what a run looks like [over there](https://github.com/casey/bendy/pull/4/checks?check_run_id=1218801742).

**Comment by casey** [comment]
Also, I could add a run of `cargo fmt`, but I think I would have to remove or update the `required_version` key of `rustfmt.toml`, to allow whatever version of cargo fmt that rustup installed.

**Comment by 0ndorio** [comment]
> Also, I could add a run of `cargo fmt`, but I think I would have to remove or update the `required_version` key of `rustfmt.toml`, to allow whatever version of cargo fmt that rustup installed.

I just updated the `required_version` to `v1.4.21` on master, so feel free to do the same on your branch :)

**Comment by casey** [comment]
Rebased on master, and added a formatting check. Since the rustfmt.toml uses nightly features, I also added a build step to install rust nightly. I could make all the tests run under nightly, which shouldn't make a difference, but would avoid installing a second toolchain. Not sure if it's worth it or not.

**Pull request merged**
